spring:
  application:
    name: video-processor

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgres:5432/video-db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: basic


url:
  analyzerAPI: http://frame-analyzer:8080