CREATE TABLE IF NOT EXISTS response (
    id UUID PRIMARY KEY NOT NULL,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    value3 DOUBLE PRECISION NOT NULL,
    value4 DOUBLE PRECISION NOT NULL,
    text TEXT NOT NULL
);